### ISSUE TITLE
Can't open streamdeck

### ISSUE THREAD

**Issue by ifuchs** [abcminiuser/python-elgato-streamdeck#112]
I'm trying to run this script <https://python-elgato-streamdeck.readthedocs.io/en/stable/examples/basic.html> from the docs and getting a cannot open deck. It is a .mk2 model. Should this work?

Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "/Users/ihf/Desktop/streamdeck.py", line 117, in <module>
    deck.open()
  File "/Users/ihf/anaconda3/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 155, in open
    self.device.open()
  File "/Users/ihf/anaconda3/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/Users/ihf/anaconda3/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.

**Comment by ifuchs** [comment]
I'm not sure what fixed this but I can now open the device and run the Device information example. Can't run the "Basic example" as there would appear to be some image files that are needed.

**Comment by ifuchs** [comment]
Found the assets. All is working.
