### ISSUE TITLE
Error on deck open

### ISSUE THREAD

**Issue by dubstech** [abcminiuser/python-elgato-streamdeck#27]
Thank you so much for creating this library.
I am running the latest 0.6.1
I have the mini, original, and XL version of the stream deck.

With the latest update, the mini seems to be working just fine.  When I try the original or the XL then with the deck.open() the follow error occurs:

Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Transport/HID.py", line 157, in write
    return self.hid.write(payload)
  File "/usr/local/lib/python3.7/dist-packages/hid/__init__.py", line 149, in write
    return self.__hidcall(hidapi.hid_write, self.__dev, data, len(data))
  File "/usr/local/lib/python3.7/dist-packages/hid/__init__.py", line 140, in __hidcall
    raise HIDException(err)
hid.HIDException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/StreamDeck/Streamdeck.py", line 99, in <module>
    deck.open()
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Devices/StreamDeck.py", line 116, in open
    self._reset_key_stream()
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Devices/StreamDeckOriginal.py", line 79, in _reset_key_stream
    self.device.write(payload)
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Transport/HID.py", line 159, in write
    raise IOError(e)
OSError: None

Any ideas on what the issue could be?

Thanks again.

**Comment by abcminiuser** [comment]
Looks like another manifestation of #25. I haven't had time this week to dig much into this other than to fix the obvious errors that were breaking the new backend on my Linux VM - I really need to break out my native Linux laptop and a Rpi on the weekend to try to replicate this.

Can you verify that you have installed the `hid` package from PyPi, and run `sudo apt-get install libhidapi-libusb0` on your machine to install the required backend?

**Comment by dubstech** [comment]
Yes, I checked again and both those items are installed and on the latest.

Again, the mini works fine which I find interesting, so has to be something different about the original and XL which both don't work.

Also, do you have a way to donate money to this cause?

**Comment by abcminiuser** [comment]
See https://github.com/abcminiuser/python-elgato-streamdeck/issues/26#issuecomment-546548134 - try removing the `libhidapi-hidraw0` package from your system, as the HID library will preference that (which doesn't work) over the `libhidapi-libusb0` package, which *should* work.

I do have a PayPal on [my creaky old website](http://www.fourwalledcubicle.com) for donations which are appreciated, but not neccesary. My library is just building on top of a tower of other's work.

**Comment by dubstech** [comment]
I can confirm that removing the libhidapi-hidraw0 does make the original work.  Now my mini and original work fine, but the XL now has the issue #25 .  The deck does open, but the keys are black and it errors out.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Transport/HID.py", line 157, in write
    return self.hid.write(payload)
  File "/usr/local/lib/python3.7/dist-packages/hid/__init__.py", line 149, in write
    return self.__hidcall(hidapi.hid_write, self.__dev, data, len(data))
  File "/usr/local/lib/python3.7/dist-packages/hid/__init__.py", line 140, in __hidcall
    raise HIDException(err)
hid.HIDException: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Documents/StreamDeck/Streamdeck.py", line 108, in <module>
    update_key_image(deck, key, False)
  File "/home/pi/Documents/StreamDeck/Streamdeck.py", line 69, in update_key_image
    deck.set_key_image(key, image)
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Devices/StreamDeckXL.py", line 185, in set_key_image
    self.device.write(payload)
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Transport/HID.py", line 159, in write
    raise IOError(e)
OSError: None

**Comment by abcminiuser** [comment]
The HIDRAW module not working on the original decks makes sense after reading through the source for it -- for some baffling reason the module developers decided to impose a maximum 4KB report size when sending or receiving reports, but the StreamDeck original uses a sequence of ~7KB reports that can't be split further. While large HID reports are uncommon they're still allowed in the spec, and I can't believe bumping this to 64KB would be too onerous on the system.

For now however, I just have to blacklist the backend. I raised an issue with the Python HID module owner to allow the transport to be skipped rather than force users to uninstall `libhid-hidraw0` but he wasn't interested, so I'll need to look a maintaining a fork.

So, with a stable backend for two out of three, I can now look at why the StreamDeck XL might be failing. Annoyingly, it looks like [this is the reason that a sensible error code isn't returned when using the libUSB backend.](https://github.com/libusb/hidapi/blob/master/libusb/hid.c#L1297).

**Comment by abcminiuser** [comment]
I'm going to close this issue now as the titular problem is now solved - best to move the discussion about the failing XL to #25 to keep everything in one place.
