### ISSUE TITLE
deck.connected() throwing error in LibUSBHIDAPI.py 

### ISSUE THREAD

**Issue by davidflypei** [abcminiuser/python-elgato-streamdeck#42]
deck.connect() is throwing an error when called.

Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
Kernel Version: 5.6.4-1-MANJARO
OS Type: 64-bit

Error:
```[david@david-manjaro Documents]$ python test.py
Found 1 Stream Deck(s).

Traceback (most recent call last):
  File "test.py", line 52, in <module>
    print_deck_info(index, deck)
  File "test.py", line 26, in print_deck_info
    print(deck.connected())
  File "/home/david/.local/lib/python3.8/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in connected
    return self.device.connected()
  File "/home/david/.local/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 321, in connected
    return any([d['path'] == self.hid_info['path'] for d in self.hidapi.enumerate()])
  File "/home/david/.local/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 147, in enumerate
    'path': current_device.path,
AttributeError: 'LP_hid_device_info' object has no attribute 'path'
Segmentation fault (core dumped)
```

Code:
```#!/usr/bin/env python3

#         Python Stream Deck Library
#      Released under the MIT license
#
#   dean [at] fourwalledcubicle [dot] com
#         www.fourwalledcubicle.com
#

# Example script that prints out information about any discovered StreamDeck
# devices to the console.

from StreamDeck.DeviceManager import DeviceManager


# Prints diagnostic information about a given StreamDeck.
def print_deck_info(index, deck):
    image_format = deck.key_image_format()

    flip_description = {
        (False, False): "not mirrored",
        (True, False): "mirrored horizontally",
        (False, True): "mirrored vertically",
        (True, True): "mirrored horizontally/vertically",
    }
    print(deck.connected())
    print("Deck {} - {}.".format(index, deck.deck_type()))
    print("\t - ID: {}".format(deck.id()))
    print("\t - Serial: '{}'".format(deck.get_serial_number()))
    print("\t - Firmware Version: '{}'".format(deck.get_firmware_version()))
    print("\t - Key Count: {} ({}x{} grid)".format(
        deck.key_count(),
        deck.key_layout()[0],
        deck.key_layout()[1]))
    print("\t - Key Images: {}x{} pixels, {} format, rotated {} degrees, {}".format(
        image_format['size'][0],
        image_format['size'][1],
        image_format['format'],
        image_format['rotation'],
        flip_description[image_format['flip']]))


if __name__ == "__main__":
    streamdecks = DeviceManager().enumerate()

    print("Found {} Stream Deck(s).\n".format(len(streamdecks)))

    for index, deck in enumerate(streamdecks):
        deck.open()
        deck.reset()

        print_deck_info(index, deck)

        deck.close()
```
I was messing with using streamdeck_ui with 0.7.2 and was running into this error so I took one of the example scripts and added `print(deck.connected())` to see if it was the UI code or this, and it seems to be this. If I comment `api.ensure_decks_connected()` in the sync function for the UI which uses connected to check and reset the device if it is disconnected, it works fine except if the stream deck disconnects and reconnects you have to restart the UI.

Other then that it seems to be working fine on Manjaro and the HIDraw blacklist issue seems to be fixed!

**Comment by abcminiuser** [comment]
Oops, sorry! My understanding of ctypes was lacking.

I've patched this in aeec0f164e64794b1324f4a226e6c66b68800324 - could you please test that before I push an updated version to PyPi?

**Comment by davidflypei** [comment]
I'll give it a shot tomorrow and let you know how it works! Thanks!

**Comment by davidflypei** [comment]
Sorry I couldn't test it earlier. The 0.7.3 version on PyPi seems to be working great! no issues so far. Thanks!
