### ISSUE TITLE
Runtime exception as of non-existing threading

### ISSUE THREAD

**Issue by redaxmedia** [abcminiuser/python-elgato-streamdeck#83]
## Issue

This library seems to have a too strong dependency on `threading` as using `deck.open()` and `deck.close()` afterwards is calling a `thread.join()`... unfortunately my application is based on `QTimer`and therfore `QThead`from `PyQt5` what results into a `RuntimeError`.

## Error

```
Exception ignored in: <function StreamDeck.__del__ at 0x117815a60>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 47, in __del__
    self._setup_reader(None)
  File "/opt/homebrew/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 133, in _setup_reader
    self.read_thread.join()
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1050, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

## Reproduce

I copied multiple parts of my application into a single file to reproduce the issue:

```
#!/usr/bin/env python3

from StreamDeck.DeviceManager import DeviceManager
from StreamDeck.ImageHelpers import PILHelper

import sys
from PyQt5.QtCore import QTimer
from PyQt5.QtWidgets import QApplication

APPLICATION = None
TIMER = None
INTERVAL = 0


def get_application() -> QApplication:
	global APPLICATION

	if APPLICATION is None:
		APPLICATION = QApplication(sys.argv)
	return APPLICATION


def get_timer() -> QTimer:
	global TIMER

	if TIMER is None:
		TIMER = QTimer()
	return TIMER


def run() -> None:
	streamdecks = DeviceManager().enumerate()

	for index, deck in enumerate(streamdecks):
		deck.open()
		image = PILHelper.create_image(deck, background = 'red')
		image_native = PILHelper.to_native_format(deck, image)

		for key in range(deck.key_count()):
			deck.set_key_image(key, image_native)

		deck.close()


def background_run() -> None:
	global INTERVAL

	timer = get_timer()

	# handle interval

	if INTERVAL == 5000:
		run()
		INTERVAL = 0
	else:
		INTERVAL += timer.interval()


if __name__ == '__main__':
	application = get_application()
	timer = get_timer()
	timer.setInterval(100)
	timer.timeout.connect(lambda: background_run())
	timer.singleShot(0, lambda: run())
	timer.start()
	sys.exit(application.exec_())
```

**Comment by abcminiuser** [comment]
Try https://github.com/abcminiuser/python-elgato-streamdeck/commit/ba1aa36ad00007341b582c9c4d393e76de5f34ed please - internally I was unconditionally joining on the reader thread (which is valid) but forgot to handle the possible exceptions that `join()` can raise.

I've updated the examples to do the same as well, and removed the unnecessary check to see if it is the current thread.

**Comment by redaxmedia** [comment]
I had no chance to give this yet but could you provide a patch release via pypi?

**Comment by abcminiuser** [comment]
Normally I prefer people test the library here before making releases, but I think the changes made are safe. I've release 0.9.0 with the fix, please re-open if you still have issues.

**Comment by redaxmedia** [comment]
I can finally confirm that device.close() is working with the latest release. Thanks
